config/routes.rb
Rails.application.routes.draw do
  resources :hardwares
  
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :employees

root 'pages#home'
get 'show' => 'employees#show'
get 'about' => 'pages#about'
get 'profile' => 'pages#profile'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
has_many :hardwares
end

app/models/hardware.rb
class Hardware < ApplicationRecord
	belongs_to :employee
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def index
		@employees = Employee.all
	end

	def new
		@employee = Employee.new
	end

	def create 
		@employee = Employee.new(employee_params)

		if @employee.save
			redirect_to @employee
		else
			render :new

		end
	end

	def edit
		@employee = Employee.find(params[:id])

		end

 def update
    	@employee = Employee.find(params[:id])
   		 if @employee.update(employee_params)
    		redirect_to @employee
    else 
    	render :show
    end
  end
  

  

def show
	@employee = Employee.find(params[:id])
end



private 
def employee_params
	params.require(:employee).permit(:employee_id, :status, :first_name, :last_name, :date_of_birth, :gender, :paersonal_email, :work_email, :mobile, :address1, :address2, :city, :postcode, :state, :country, :department, :office, :reports_to, :position_title, :start_date, :finish_date)
	end
end

app/controllers/hardwares_controller.rb
class HardwaresController < ApplicationController
def index
		@hardwares = Hardware.all
	end

	def new
		@hardware = Hardware.new
	end

	def create 
		@hardware = Hardware.new(hardware_params)

		if @hardware.save
			redirect_to @hardware
		else
			render :new

		end
	end


	def edit
		@hardware = Hardware.find(params[:id])

		end

 def update
    	@hardware = Hardware.find(params[:id])
   		 if @hardware.update(hardware_params)
    		redirect_to @hardware
    else 
    	render :show
    end
  end
  

  

def show
	@hardware = Hardware.find(params[:id])
end



private 
def hardware_params
	params.require(:hardware).permit(:asset_tag, :asset_type, :model_brand, :serial_number, :manufacture_date, :host_name, :mac_address_wifi, :mac_address_ethernet, :operating_system, :business_unit, :location, :sophos_install_date, :admin_password, :user_password, :setup_by)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
end
  	def index
		@employees = Employee.all
	end






	
  private 
def employee_params
	params.require(:employee).permit(:employee_id, :status, :first_name, :last_name, :date_of_birth, :gender, :paersonal_email, :work_email, :mobile, :address1, :address2, :city, :postcode, :state, :country, :department, :office, :reports_to, :position_title, :start_date, :finish_date)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/hardwares_helper.rb
module HardwaresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/_form.html.erb
<div class="container">


<div class="section">
  <%= simple_form_for @employee do |f| %>
  <div class="field">
    <%= f.input :first_name %>
    <%= f.input :last_name, class: "control" %>
    <%= f.input :date_of_birth, class: "control" %>
    <%= f.input :gender, collection: ["male", "female","perfer not to say"] %>
    <%= f.input :personal_email, class: "control" %>
    <%= f.input :work_email, class: "control" %>
    <%= f.input :mobile, class: "control" %>
    <%= f.input :address1, class: "control" %>
    <%= f.input :address2, class: "control" %> 
    <%= f.input :position_title, class: "control" %>     
    <%= f.input :city, class: "control" %>
    <%= f.input :postcode, class: "control" %> 
    <%= f.input :state, collection: ["QLD", "NSW","ACT","VIC","SA","WA", "NA"] %>
    <%= f.input :country, collection: ["Australia","New Zealand","Singapore","Hong Kong"] %>
    <%= f.input :start_date, class: "control" %> 
  </div>
  </div>



<div class="container">
<strong>Systems</strong>

  <div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    JobAdder
  </label>
</div>

<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Bullhorn
  </label>
</div>

<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Astute Perm Payroll 
  </label>
</div>


<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Nexus 
  </label>
</div>
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    NetSuite
  </label>
</div>

<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Astute Payroll Officer 
  </label>
</div>

<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    FlexiPurchase
  </label>
</div>
</div>

<div class='container pull-right'>

<strong>Hardware</strong>
<div class="form-check pull-right">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Mobile Phone
  </label>
</div>

<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Desk Phone
  </label>
</div>
</div>



<%= f.button :submit, class: "botton is-primary" %> 

<% end %>
</div>

app/views/employees/edit.html.erb
<div class="container">
<center><h1>Edit Employee</h1></center>
</div>

<% content_for :update_employee, "edit employee" %>
<%= render 'form' %>

<%= link_to 'show', employees_path %>
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<div class="container">

<h1>Employees</h1>



      <div class="table-responsive">
        <table class="table table-bordered">
          
           <tr> 

      <th>ID</th>
      <th>Status</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Date of Birth</th>
      <th>Gender</th>
      <th>Mobile</th>
      <th>Country</th>
      <th>Department</th>
      <th>Office</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to employee.id, employee %></td>
        <td><%= employee.status %></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.gender %></td>
        <td><%= employee.mobile %></td>
        <td><%= employee.country %></td>
        <td><%= employee.department %></td>
        <td><%= employee.office %></t>
              </tr>
    <% end %>
  </tbody>
</table>
</div>
</tr>
</thead>
</table>

<br>

 <centre><%= link_to 'New Employee', new_employee_path %></centre>






    

     
    

app/views/employees/new.html.erb
<div class="container">
<center><h1>New Employee</h1></center>
</div>


<% content_for :employee, "new employee" %>
<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog" alt=""/>
                            <div class="file btn btn-lg btn-primary">
                                Change Photo
                                <input type="file" name="file"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                       <%= @employee.first_name %> <%= @employee.last_name %>
                                    </h5>
                                    <h6>
                                        <%= @employee.position_title %>
                                    </h6>
                                    <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Job Details</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/><%= link_to 'Edit', edit_employee_path %>

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>WORK LINK</p>
                            <a href=""><%= @employee.work_email %></a><br/>
                            <a href="">LinkedIn link</a><br/>
                            <a href="">Bootply Profile</a>
                            <p>SKILLS</p>
                            <a href="">Web Designer</a><br/>
                            <a href="">Web Developer</a><br/>
                            <a href="">WordPress</a><br/>
                            <a href="">WooCommerce</a><br/>
                            <a href="">PHP, .Net</a><br/>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>User Id</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.id %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.first_name %> <%= @employee.last_name %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Gender</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.gender %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Date of Birth</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.date_of_birth %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Personal Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.personal_email %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Mobile</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.mobile %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Position Title</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.position_title %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Address</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.address1 %> <%= @employee.address2 %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>City</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.city %></p>
                                            </div>
                                        </div>
                                            <div class="row">
                                            <div class="col-md-6">
                                                <label>Postcode</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.postcode %></p>
                                            </div>
                                        </div>
                                          <div class="row">
                                            <div class="col-md-6">
                                                <label>State</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @employee.state %></p>
                                            </div>
                                        </div>

                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Job Title</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>link to job title</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>start_date</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>link to start date</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>office</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>link to office</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Link to department</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>TFR</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>link to TFN</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>6 months</p>
                                            </div>
                                        </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Your Bio</label><br/>
                                        <p>Your detail description</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>           
        </div>
        <%= link_to 'Edit', edit_employee_path %> |

    <%= link_to 'Back', employees_path %>
  </div>
</div>

app/views/hardwares/_form.html.erb
form

<div class="container">
<%= simple_form_for(@hardware) do |f| %>
<div class="form-inputs">
  </div>
  <%= f.input :status, collection: ["Active", "Ready to Deploy", "Needs Repair", "End of Life",] %>
<%= f.input :asset_tag %>
<%= f.input :asset_type, collection: ["Montior", "Desktop","Laptop","Mobile Phone",]%>
<%= f.input :model_brand %>
<%= f.input :serial_number %>
<%= f.input :manufacture_date %>
<%= f.input :host_name %>
<%= f.input :mac_address_ethernet %>
<%= f.input :mac_address_wifi %>
<%= f.input :operating_system %>
<%= f.input :business_unit, collection: ["Rubicor Group", "Rubicor Workforce", "Rubicor Governemnt", "Rubicor Technical", "GR/N", "Xpand"] %>
<%= f.input :location, collection: ["Mackay", "Queen Street", "Wacol", "Newcastle", "Parramatta", "Pitt St", "Canberra", "Collin Street", "Campbellfield", "Mt Waverly", "Adelaide", "Perth", "Singapore", "Hong Kong"] %>
<%= f.input :sophos_install_date %>
<%= f.input :admin_password %>
<%= f.input :user_password %>
<%= f.input :setup_by %>
<%= f.input :employee_id %>

<div class="form-actions">
    <%= f.button :submit %>

<% end %>
</div>

app/views/hardwares/edit.html.erb
edit
<h1>Editing Asset</h1>

<%= render 'form', hardware: @hardware %>

<%= link_to 'Show', @hardware %> |
<%= link_to 'Back', hardware_path %>

app/views/hardwares/index.html.erb
index
<div class="container">

<h1>Assets</h1>





      <div class="table-responsive">
        <table class="table table-bordered">
          
           <tr> 

      
      <th>Asset Tag</th>
      <th>Asset Type</th>
      <th>Status</th>
      <th>Allocated To</th>
      
    </tr>
  </thead>

  <tbody>
    <% @hardwares.each do |hardware| %>
      <tr>
        
        <td><%= link_to hardware.asset_tag, hardware %></td>
        <td><%= hardware.asset_type %></td>
        <td><%= hardware.status %></td>
        <td><%= hardware.employee_id %></td>
        
              </tr>
    <% end %>
  </tbody>
</table>
</div>
</tr>
</thead>
</table>

<br>

 <centre><%= link_to 'New Asset', new_hardware_path %></centre>

app/views/hardwares/new.html.erb
new
<h1>New Asset</h1>

<%= render 'form', hardware: @hardware %>

<%= link_to 'Show', @hardware %> |
<%= link_to 'Back', hardwares_path %>

app/views/hardwares/show.html.erb
show
<div class="container">

<div class="row"> 
<div class="col-md-6">
<label>Asset Id</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.id %></p>
  </div>

 <div class="col-md-6">
<label>Asset Status</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.status %></p>
  </div>


<div class="col-md-6">
<label>Asset Tag</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.asset_tag %></p>
  </div>
  
  <div class="col-md-6">
<label>Asset Type</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.asset_type %></p>
  </div>

  <div class="col-md-6">
<label>Model/Brand</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.model_brand %></p>
  </div>

  <div class="col-md-6">
<label>Serial Number</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.serial_number %></p>
  </div>
<div class="col-md-6">
<label>Manufacture Date</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.manufacture_date %></p>
  </div>
  
  <div class="col-md-6">
<label>Host Name</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.host_name %></p>
  </div>

  <div class="col-md-6">
<label>Mac Address Wifi</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.mac_address_wifi %></p>
  </div>

  <div class="col-md-6">
<label>Mac Address Ethernet</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.mac_address_ethernet %></p>
  </div>

  <div class="col-md-6">
<label>Operating System</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.operating_system %></p>
  </div>

  <div class="col-md-6">
<label>Department</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.business_unit %></p>
  </div>
<div class="col-md-6">
<label>Office</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.location %></p>
  </div>
  
  <div class="col-md-6">
<label>Sophos Install</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.sophos_install_date %></p>
  </div>

  <div class="col-md-6">
<label>Admin Password</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.admin_password %></p>
  </div>

  <div class="col-md-6">
<label>User Password</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.user_password %></p>
  </div>
   <div class="col-md-6">
<label>Setup By</label>
</div>
 <div class="col-md-6">
  <p><%= @hardware.setup_by %></p>
  </div>
</div>
 <%= link_to 'Edit', edit_hardware_path %> |

    <%= link_to 'Back', hardwares_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HutchTec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>
  

  <body>

    <!-- Navigation Bar -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <%= link_to "HutchTec", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav"></ul>
          
         </ul> 
          
       
      </div>
    </nav>

    <!-- Flash Messages -->
    

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© HutchTec Design</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/layouts/navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark d-flex-none">
  <button class="btn btn-link text-white pl-0" type="button" data-toggle="sidebar">
    <i class="material-icons align-middle md-36">short_text</i>
  </button>
  <div class="page-title m-0">Dashboard</div>

  <div class="collapse navbar-collapse" id="mainNavbar">
    <ul class="navbar-nav ml-auto align-items-center">
      <li class="nav-item dropdown notifications d-flex align-self-center align-items-center" id="navbarNotifications">
        <a href="#" class="nav-link dropdown-toggle notifications--active" data-toggle="dropdown" aria-expanded="false">
          <i class="material-icons align-middle">notifications</i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="notificationsDropdown" id="notificationsDropdown">
          <ul class="nav nav-tabs-notifications d-flex px-0" id="notifications-ul" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="notifications-tab" data-toggle="tab" href="#notifications" role="tab" aria-controls="notifications"
                aria-selected="true">Notifications</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="alerts-tab" data-toggle="tab" href="#alerts" role="tab" aria-controls="alerts" aria-selected="false">Alerts</a>
            </li>
          </ul>
          <div class="tab-content" id="notifications-tabs">
            <div class="tab-pane fade show active" id="notifications" role="tabpanel" aria-labelledby="notifications-tab">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <div class="w-100">
                    <a href="#">john</a> received a new quote</div>
                  <div class="w-100 text-muted">4 secs ago</div>
                </li>
                <li class="list-group-item">
                  <div class="w-100">
                    <a href="#">karen</a> received a new quote</div>
                  <div class="w-100 text-muted">25 mins ago</div>
                </li>
                <li class="list-group-item">
                  <div class="w-100">
                    <a href="#">jim</a> received a new quote</div>
                  <div class="w-100 text-muted">7 hrs ago</div>
                </li>
                <li class="list-group-item text-right">
                  <a href="#">
                    <span class="align-middle">View All</span>
                    <i class="material-icons md-18 align-middle">arrow_forward</i>
                  </a>
                </li>
              </ul>
            </div>
            <div class="tab-pane fade" id="alerts" role="tabpanel" aria-labelledby="alerts-tab">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <div class="media align-items-center">
                    <i class="material-icons align-middle mr-2 text-warning">
                      info_outline
                    </i>
                    <div class="media-body">
                      <div class="w-100">
                        <a href="profile.html">john</a> received a new
                        <a href="#">quote</a>
                      </div>
                      <div class="w-100 text-muted">4 secs ago</div>
                    </div>
                  </div>
                </li>
                <li class="list-group-item">
                  <div class="media align-items-center">
                    <i class="material-icons align-middle mr-2 text-success">
                      check_circle
                    </i>
                    <div class="media-body">
                      <div class="w-100">
                        <a href="profile.html">karen</a> completed a
                        <a href="#">task</a>
                      </div>
                      <div class="w-100 text-muted">25 mins ago</div>
                    </div>
                  </div>
                </li>
                <li class="list-group-item">
                  <div class="media align-items-center">
                    <i class="material-icons align-middle mr-2 text-danger">
                      warning
                    </i>
                    <div class="media-body">
                      <div class="w-100">
                        <a href="profile.html">jim</a> removed a
                        <a href="#">task</a>
                      </div>
                      <div class="w-100 text-muted">7 hrs ago</div>
                    </div>
                  </div>
                </li>
                <li class="list-group-item text-right">
                  <a href="#">
                    <span class="align-middle">View All</span>
                    <i class="material-icons md-18 align-middle">arrow_forward</i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </li>
      <li class="nav-item nav-divider">
      <li class="nav-item">
        <a href="#" class="nav-link">
          Frontted
          <img src="https://pbs.twimg.com/profile_images/928893978266697728/3enwe0fO_400x400.jpg" class="img-fluid rounded-circle ml-1" width="35"
            alt="">
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>